### ISSUE TITLE
Accès à la documentation

### ISSUE THREAD

**Issue by sylvain-m** [dsi-cen/kollect#22]
Bonjour,
Je découvre le dépôt de Kollect à l'instant 👍 
Je voulais consulter la documentation https://docs.kollect.fr/ , mais je reçois :

> Service Unavailable
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by rylebrun** [comment]
Bonjour @sylvain-m, merci du retour, problème réglé.

**Comment by sylvain-m** [comment]
Merci :)
Par contre, j'ai tenté d'ouvrir cette page depuis la doc, et ça ne fonctionne pas :
https://docs.kollect.fr/documentation/installation/
Désolé pour le dérangement 😉

**Comment by sylvain-m** [comment]
Je viens de trouver la bonne URL :
https://docs.kollect.fr/installation/installation/
(le lien était celui de la page principale)
