### ISSUE TITLE
Suppression d'une observation avec un commentaire associé

### ISSUE THREAD

**Issue by rylebrun** [dsi-cen/kollect#9]
On ne peut pas supprimer une observation quand un commentaire est attaché à l'observation.
Cela est dû à la clé étrangère dans la table _site.comobs_ qui référence l'_idobs_ de la table _obs.obs_. 
Dans le code, il n'y a pas de suppression du _comobs_ donc impossible de supprimer l'_obs_ si elle est déjà référencée dans une autre table.
Il faut rajouter la suppression du _comobs_ dans le code ou le gérer en base de donnée.

**Comment by tomgachet** [comment]
Je propose de gérer ça directement en base de donnée : ajout du paramètre ON DELETE CASCADE à la clé étrangère de la table _site.comobs_ qui référence l'_idobs_ de la table _obs.obs_.
Ainsi, lors de la suppression d'une observation avec un commentaire attaché, celui-ci sera automatiquement supprimé dans la table _comobs_

**Comment by tomgachet** [comment]
Réglé ce jour
